"""create precedents table

Revision ID: 6a8e0d52b439
Revises: 6cd2f00dabe2
Create Date: 2026-09-19 13:41:31.646093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a8e0d52b439'
down_revision: Union[str, Sequence[str], None] = '6cd2f00dabe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precedents',
    sa.Column('precedent_id', sa.String(length=20), nullable=False),
    sa.Column('case_name', sa.TEXT(), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=True),
    sa.Column('court', sa.String(length=50), nullable=True),
    sa.Column('decision_date', sa.DATE(), nullable=True),
    sa.Column('decision_type', sa.String(length=20), nullable=True),
    sa.Column('source_url', sa.TEXT(), nullable=True),
    sa.Column('label', sa.String(length=20), nullable=True),
    sa.Column('holding', sa.TEXT(), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('referenced_statutes', sa.TEXT(), nullable=True),
    sa.Column('referenced_precedents', sa.TEXT(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('raw_text', sa.TEXT(), nullable=False),
    sa.Column('fetched_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('precedent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('precedents')
    # ### end Alembic commands ###
