"""create_law_tables

Revision ID: b714fd4ea8de
Revises: 
Create Date: 2026-04-06 17:45:14.864737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b714fd4ea8de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mst', sa.String(length=20), nullable=False),
    sa.Column('law_id', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('promulgation_date', sa.DATE(), nullable=True),
    sa.Column('enforcement_date', sa.DATE(), nullable=True),
    sa.Column('fetched_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mst')
    )
    op.create_table('law_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('law_id', sa.Integer(), nullable=False),
    sa.Column('jo_code', sa.String(length=10), nullable=True),
    sa.Column('article_number', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('full_text', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['law_id'], ['laws.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('law_id', 'jo_code')
    )
    op.create_table('law_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_law_id', sa.Integer(), nullable=False),
    sa.Column('child_law_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['child_law_id'], ['laws.id'], ),
    sa.ForeignKeyConstraint(['parent_law_id'], ['laws.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_law_id', 'child_law_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('law_relations')
    op.drop_table('law_articles')
    op.drop_table('laws')
    # ### end Alembic commands ###
